name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: asdf-vm/actions/install@v3
            - run: scarb fmt --check

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: asdf-vm/actions/install@v3
            - run: scarb test

    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: asdf-vm/actions/install@v3
            - run: curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh
            - run: snforge test --coverage
            - run: npx jest --coverage
            - uses: codecov/codecov-action@v5
              with:
                file: ./coverage.lcov
                token: ${{ secrets.CODECOV_TOKEN }}
                slug: keep-starknet-strange/tokenized-bond
